# nexa-license — Nexa 계열 공용 라이선스 라이브러리(형식 · 서명 체인 검증 · 기기 ID · 리스 프로토콜).
# 설계 SSOT = SosomLab/nexa-sql docs/23(정품 인증) · docs/25(티어 · 인증 서버 · 저장소 분리 · §10 범용성).
# 소비자: nexa-sql(nsql-license) · nexa-clip · nexa-beep · nexa-dir2 · 비공개 nexa-license-server(nexa-licensed · nexa-license-tool).
# 원칙: 라이브러리는 앱을 모른다 — Feature 열거형·UI 문자열·저장 폴더 정책은 호출측이 주입. 기본 의존 0.
[workspace]
resolver = "2"
members = ["crates/nexa-license"]

[workspace.package]
version = "0.0.1"
edition = "2021"
rust-version = "1.82"
license = "LicenseRef-PolyForm-Noncommercial-1.0.0"
authors = ["Sangyong Bae <kiros33@gmail.com>"]
repository = "https://github.com/SosomLab/nexa-license"
homepage = "https://sosomlab.com"

[workspace.lints.rust]
missing_debug_implementations = "warn"
unreachable_pub = "warn"

[workspace.lints.clippy]
redundant_clone = "warn"
inefficient_to_string = "warn"
unwrap_used = "warn"
